import React from 'react';
import type { BankTransaction, Party } from '../types/tax';
import { Landmark, CheckCircle2, ArrowDownLeft, ArrowUpRight, Sparkles, Check } from 'lucide-react';

const formatINR = (val: number): string => typeof val === 'number' && !isNaN(val) ? '₹' + Math.round(val).toLocaleString('en-IN') : '₹0';
interface BankReconciliationProps { bankTransactions?: BankTransaction[]; transactions?: BankTransaction[]; parties?: Party[]; onApproveReconciliation?: (id: string) => void; onManualMatch?: (id: string) => void; }

export const BankReconciliation: React.FC<BankReconciliationProps> = ({ bankTransactions, transactions, onApproveReconciliation, onManualMatch }) => {
  const txns = bankTransactions || transactions || [];
  const handleApprove = onApproveReconciliation || onManualMatch || (() => {});
  return <div className="space-y-6 animate-fadeIn">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-4 sm:p-6 rounded-2xl border border-slate-200 shadow-md"><div className="min-w-0"><h2 className="text-lg sm:text-xl font-bold text-slate-900 flex items-start gap-2"><Landmark className="w-6 h-6 text-emerald-600 shrink-0" /> <span>Bank Statement Auto-Reconciliation Engine</span></h2><p className="text-xs text-slate-500 mt-1">Upload HDFC statement → AI fuzzy matcher pairs bank narrations against ledgers.</p></div><div className="shrink-0 flex items-center gap-2 bg-emerald-50 border border-emerald-200 px-3 py-2 rounded-xl text-emerald-700 text-[11px] font-bold"><Sparkles className="w-4 h-4" /> Matcher Active</div></div>
    <div className="bg-white border border-slate-200 rounded-2xl shadow-md overflow-hidden"><div className="p-4 border-b border-slate-100"><div className="text-xs font-bold text-slate-800">Statement Lines ({txns.length})</div><div className="text-[10px] text-slate-400 mt-1">Review the suggested match and approve directly from your phone.</div></div><div className="divide-y divide-slate-100">{txns.map(bt => { const isCredit = bt.type === 'CREDIT'; const isReconciled = bt.status === 'RECONCILED'; return <div key={bt.id} className={`p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${isReconciled ? 'bg-emerald-50/30' : ''}`}><div className="flex items-start gap-3 min-w-0"><div className={`p-2 rounded-xl border shrink-0 ${isCredit ? 'bg-emerald-50 border-emerald-200 text-emerald-600' : 'bg-red-50 border-red-200 text-red-600'}`}>{isCredit ? <ArrowDownLeft className="w-5 h-5" /> : <ArrowUpRight className="w-5 h-5" />}</div><div className="min-w-0"><div className="text-xs text-slate-400">{bt.date}</div><div className="text-sm font-bold text-slate-800 mt-0.5 break-words">{bt.narration}</div><div className="text-xs text-slate-500 mt-1 flex flex-wrap items-center gap-2"><span>UTR: <span className="font-mono break-all">{bt.utr}</span></span>{bt.matchedParty && <span className="px-2 py-1 bg-blue-50 text-blue-700 rounded text-[10px] font-bold break-words">Matched: {bt.matchedParty}</span>}</div></div></div><div className="flex flex-col xs:flex-row sm:items-center justify-between sm:justify-end gap-3 sm:gap-6"><div className="text-left sm:text-right"><div className={`text-base font-bold font-mono ${isCredit ? 'text-emerald-600' : 'text-slate-900'}`}>{isCredit ? '+' : '-'}{formatINR(bt.amount)}</div><div className="text-[10px] font-bold text-slate-400 mt-0.5 uppercase">{bt.type}</div></div>{isReconciled ? <span className="w-full sm:w-auto flex items-center justify-center gap-1.5 px-3 py-2 bg-emerald-100 text-emerald-800 rounded-xl text-xs font-bold"><CheckCircle2 className="w-4 h-4" /> Reconciled</span> : <button onClick={() => handleApprove(bt.id)} className="w-full sm:w-auto min-h-11 flex items-center justify-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-md"><Check className="w-3.5 h-3.5" /> Approve Match</button>}</div></div>; })}</div></div>
  </div>;
};