import React, { useState } from 'react';
import type { SalesInvoice, PurchaseInvoice } from '../types/tax';
import { downloadTallySalesXml, downloadTallyExcelTemplate } from '../utils/tallyExporter';
import { applyTallyMasters, fetchTallyCompanies, pullTallyDaybook, syncTally, testTallyConnection } from '../services/api';
import { FileSpreadsheet, Download, CheckCircle2, Code, Wifi, RefreshCw, Upload, Database, ArrowDownToLine, AlertCircle, ShieldCheck } from 'lucide-react';
interface TallyExportModuleProps { salesInvoices: SalesInvoice[]; purchaseInvoices: PurchaseInvoice[]; }
type ApplyPreview = { companyName:string; existingParties:number; newParties:number; existingStockItems:number; newStockItems:number; items:{entityType:string;tallyName:string;action:string;matchType:string;score:number;gstin?:string}[] };
type ApplyResponse = { mode:'preview'; preview:ApplyPreview; note:string }; type ApplyResult={success:boolean;companyName:string;partiesCreated:number;stockItemsCreated:number;skipped:number;errors:string[]};
export const TallyExportModule: React.FC<TallyExportModuleProps> = ({salesInvoices,purchaseInvoices}) => {
 const [baseUrl,setBaseUrl]=useState('http://localhost:9000'),[companyName,setCompanyName]=useState('Apex Electronics & Traders'),[status,setStatus]=useState('Not connected'),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[lastResponse,setLastResponse]=useState(''),[applyPreview,setApplyPreview]=useState<ApplyPreview|null>(null);
 const run=async(work:()=>Promise<void>)=>{setBusy(true);try{await work()}catch(e){setStatus(e instanceof Error?e.message:'Tally operation failed');setConnected(false)}finally{setBusy(false)}};
 const connect=()=>run(async()=>{const r=await testTallyConnection(baseUrl,companyName||undefined);setConnected(r.connected);setStatus(r.message);setLastResponse(r.rawResponse??'')});
 const discover=()=>run(async()=>{const r=await fetchTallyCompanies(baseUrl);setConnected(r.connected);setStatus(r.message);setLastResponse(r.rawResponse??'');if(r.companyName)setCompanyName(r.companyName)});
 const push=(data:'all'|'masters'|'sales'|'purchases')=>run(async()=>{const r=await syncTally(baseUrl,companyName,data);setConnected(r.success);setStatus(r.results.map(x=>x.message).join(' | '));setLastResponse(r.results.at(-1)?.rawResponse??'')});
 const pull=()=>run(async()=>{const to=new Date().toISOString().slice(0,10),d=new Date();d.setDate(d.getDate()-30);const r=await pullTallyDaybook(baseUrl,companyName,d.toISOString().slice(0,10),to);setConnected(r.result.connected);setStatus(r.result.message);setLastResponse(r.result.rawResponse??'')});
 const previewApply=()=>run(async()=>{const r=await applyTallyMasters(baseUrl,companyName,false) as ApplyResponse;setApplyPreview(r.preview);setStatus(`Preview ready: ${r.preview.newParties} new parties and ${r.preview.newStockItems} new stock items.`)});
 const confirmApply=()=>run(async()=>{const r=await applyTallyMasters(baseUrl,companyName,true) as ApplyResult;setApplyPreview(null);setStatus(r.success?`Applied ${r.partiesCreated} parties and ${r.stockItemsCreated} stock items; ${r.skipped} existing records skipped.`:`Apply completed with ${r.errors.length} error(s).`);setLastResponse(r.errors.join('\n'))});
 return <div className="space-y-6 animate-fadeIn">
  <div className="bg-gradient-to-r from-blue-700 via-indigo-700 to-cyan-700 p-4 sm:p-6 rounded-2xl shadow-md text-white"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="min-w-0"><h2 className="text-lg sm:text-xl font-bold flex items-start gap-2"><Database className="w-6 h-6 text-cyan-300 shrink-0"/><span>TallyPrime Advanced Integration Hub</span></h2><p className="text-xs text-blue-100 mt-1">Live HTTP/XML bridge for masters, sales, purchases and read-only daybook pull.</p></div><div className="px-3 py-2 rounded-xl text-xs font-bold flex items-center gap-2 bg-white/10 shrink-0"><span className={`w-2 h-2 rounded-full ${connected?'bg-emerald-300':'bg-slate-300'}`}/>{connected?'Tally Connected':'Tally Not Connected'}</div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4"><label className="text-xs font-semibold text-blue-100">Tally URL<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} className="mt-1 w-full rounded-lg bg-white text-slate-900 px-3 py-2 min-h-11 outline-none"/></label><label className="text-xs font-semibold text-blue-100 md:col-span-2">Tally Company<input value={companyName} onChange={e=>setCompanyName(e.target.value)} className="mt-1 w-full rounded-lg bg-white text-slate-900 px-3 py-2 min-h-11 outline-none"/></label></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-3"><button disabled={busy} onClick={connect} className="min-h-11 px-4 py-2 rounded-lg bg-white text-slate-900 text-xs font-bold flex items-center justify-center gap-2"><Wifi className="w-4 h-4"/> Test Connection</button><button disabled={busy} onClick={discover} className="min-h-11 px-4 py-2 rounded-lg bg-white/10 border border-white/20 text-white text-xs font-bold flex items-center justify-center gap-2"><RefreshCw className="w-4 h-4"/> Discover Company</button></div><div className="mt-3 text-xs text-blue-100 break-words"><span className="font-semibold">Status:</span> {busy?'Working…':status}</div></div>
  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3">{[['masters','Push Masters','Customers, vendors and stock items.',Upload,'text-blue-600'],['preview','Preview Tally → TaxFlow','Review masters before writing locally.',ShieldCheck,'text-emerald-600'],['sales','Push Sales','Send sales vouchers with GST and inventory.',CheckCircle2,'text-emerald-600'],['purchases','Push Purchases','Send purchase vouchers with input GST.',Upload,'text-orange-600'],['pull','Pull Daybook','Read the last 30 days for reconciliation.',ArrowDownToLine,'text-purple-600']].map(([action,title,desc,Icon,iconClass])=><button key={String(action)} disabled={busy||!companyName} onClick={()=>action==='preview'?previewApply():action==='pull'?pull():push(action as 'masters'|'sales'|'purchases')} className="text-left bg-white border border-slate-200 rounded-2xl p-4 sm:p-5 shadow-md hover:border-blue-400 disabled:opacity-50 min-h-32"><Icon className={`w-5 h-5 mb-3 ${iconClass}`}/><div className="font-bold text-sm">{title}</div><p className="text-xs text-slate-500 mt-1">{desc}</p></button>)}</div>
  {applyPreview&&<div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-4 sm:p-5 shadow-md space-y-4"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="font-bold text-emerald-950">Tally → TaxFlow master preview</div><div className="text-xs text-emerald-800 mt-1">{applyPreview.newParties} new parties · {applyPreview.newStockItems} new stock items · {applyPreview.existingParties+applyPreview.existingStockItems} existing matches</div></div><button disabled={busy} onClick={confirmApply} className="w-full sm:w-auto min-h-11 px-4 py-2 rounded-lg bg-emerald-700 text-white text-xs font-bold">Confirm &amp; Apply</button></div><div className="max-h-56 overflow-auto rounded-xl bg-white border border-emerald-100">{applyPreview.items.length===0?<div className="p-4 text-xs text-slate-500">No master changes are required.</div>:applyPreview.items.map((item,i)=><div key={`${item.entityType}-${item.tallyName}-${i}`} className="px-4 py-3 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-1 text-xs"><span className="font-semibold break-words">{item.entityType}: {item.tallyName}</span><span className="text-slate-500">{item.action} · {item.matchType} · {item.score.toFixed(2)}</span></div>)}</div></div>}
  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-6">{[['Excel Fallback','For firms without HTTP access, export the existing Tally-compatible workbook.',()=>downloadTallyExcelTemplate(salesInvoices,purchaseInvoices),'Export Excel',FileSpreadsheet,'text-emerald-600'],['XML File Fallback','Generate a file when direct network access to Tally is unavailable.',()=>downloadTallySalesXml(salesInvoices),'Download Sales XML',Download,'text-blue-600'],['TDL Ready','Backend is designed around Tally native HTTP/XML integration.',null,'Tally HTTP Gateway → TaxFlow API',Code,'text-purple-600']].map(([title,desc,fn,label,Icon,cls])=><div key={String(title)} className="bg-white border border-slate-200 rounded-2xl p-4 sm:p-5 shadow-md space-y-3"><div className="flex items-center gap-2 text-sm font-bold"><Icon className={`w-5 h-5 ${cls}`}/>{title}</div><p className="text-xs text-slate-600">{desc}</p>{fn?<button onClick={fn as ()=>void} className="min-h-10 text-xs font-bold px-3 py-2 rounded-lg bg-slate-50">{label}</button>:<div className="p-3 bg-purple-50 rounded-xl text-[11px] text-purple-900 font-mono break-words">{label}</div>}</div>)}</div>
  {lastResponse&&<div className="bg-slate-950 rounded-2xl p-4 sm:p-5 text-xs text-slate-200 shadow-md"><div className="flex items-center gap-2 font-bold mb-3"><AlertCircle className="w-4 h-4"/> Last Tally response</div><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-all">{lastResponse}</pre></div>}
 </div>;
};